spring.application.name=appointment-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/appointment_db
spring.datasource.username=appointment_user
spring.datasource.password=appointment_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true